import * as React from 'react';
import {
    Activity,
    Archive,
    ArrowLeftRight,
    Calendar,
    ChevronRight,
    CircleMinus,
    BarChart3,
    Bell,
    Bug,
    CloudOff,
    ClipboardCopy,
    ChevronDown,
    ChevronUp,
    Circle,
    CircleAlert,
    CircleCheckBig,
    CircleHelp,
    CirclePlay,
    CirclePlus,
    CircleStop,
    CircleUserRound,
    CircleX,
    Clock3,
    Code,
    CornerDownLeft,
    Cpu,
    Download,
    Eye,
    EyeOff,
    FileCode2,
    FileText,
    Fingerprint,
    FlaskConical,
    Flame,
    Folder,
    Gauge,
    GitCommitHorizontal,
    GitBranch,
    Globe,
    Grid2x2,
    Hammer,
    Heart,
    House,
    Keyboard,
    KeyRound,
    Languages,
    Laptop,
    Library,
    Lightbulb,
    Link,
    List,
    Lock,
    LogIn,
    LogOut,
    TriangleAlert,
    Mic,
    Minimize2,
    Monitor,
    Moon,
    Palette,
    Pencil,
    Play,
    Plus,
    Puzzle,
    QrCode,
    Radio,
    RefreshCw,
    Search,
    Server,
    ShieldCheck,
    Shield,
    SlidersHorizontal,
    Smartphone,
    Sparkles,
    Sun,
    Tag,
    Terminal,
    Timer,
    Type,
    User,
    UserPlus,
    Users,
    Wrench,
    X,
    Zap,
    type LucideIcon,
} from 'lucide-react-native';

const ICON_MAP = {
    add: Plus,
    'add-outline': Plus,
    'add-circle-outline': CirclePlus,
    'albums-outline': Library,
    'alert-circle-outline': CircleAlert,
    'analytics-outline': BarChart3,
    'apps-outline': Grid2x2,
    'archive-outline': Archive,
    'bulb-outline': Lightbulb,
    'calendar-outline': Calendar,
    'bug-outline': Bug,
    checkmark: CircleCheckBig,
    'checkmark-circle': CircleCheckBig,
    'checkmark-circle-outline': CircleCheckBig,
    'checkmark-done-outline': CircleCheckBig,
    'chevron-down': ChevronDown,
    'chevron-forward': ChevronRight,
    'chevron-up': ChevronUp,
    close: X,
    'close-circle': CircleX,
    'close-circle-outline': CircleX,
    'cloud-offline-outline': CloudOff,
    'code-outline': Code,
    'code-slash': Code,
    'code-slash-outline': Code,
    'code-working-outline': FileCode2,
    'color-palette-outline': Palette,
    'construct-outline': Wrench,
    'contract-outline': Minimize2,
    'contrast-outline': Circle,
    'create-outline': Pencil,
    'desktop-outline': Monitor,
    'document-text-outline': FileText,
    'download-outline': Download,
    ellipse: Circle,
    'eye-off-outline': EyeOff,
    'eye-outline': Eye,
    'exit-outline': LogOut,
    'flame-outline': Flame,
    'flash-outline': Zap,
    'flask-outline': FlaskConical,
    'folder-outline': Folder,
    'finger-print-outline': Fingerprint,
    'git-branch-outline': GitBranch,
    'git-commit-outline': GitCommitHorizontal,
    'globe-outline': Globe,
    'hammer-outline': Hammer,
    'hardware-chip-outline': Cpu,
    heart: Heart,
    'heart-outline': Heart,
    'help-circle-outline': CircleHelp,
    'home-outline': House,
    'hourglass-outline': Timer,
    'information-circle': CircleHelp,
    'information-circle-outline': CircleHelp,
    'key-outline': KeyRound,
    'keypad-outline': Keyboard,
    'language-outline': Languages,
    'laptop-outline': Laptop,
    'link-outline': Link,
    'list-outline': List,
    'lock-closed-outline': Lock,
    'lock-closed': Lock,
    'log-in': LogIn,
    'log-out': LogOut,
    'log-out-outline': LogOut,
    'logo-github': GitBranch,
    'mic-outline': Mic,
    'moon-outline': Moon,
    'notifications-outline': Bell,
    'options-outline': SlidersHorizontal,
    person: User,
    'person-add-outline': UserPlus,
    'person-outline': User,
    pencil: Pencil,
    'people-outline': Users,
    'person-circle-outline': CircleUserRound,
    'phone-portrait-outline': Smartphone,
    'play-circle-outline': CirclePlay,
    play: Play,
    'pricetag-outline': Tag,
    'pulse-outline': Activity,
    'qr-code-outline': QrCode,
    'radio-outline': Radio,
    'refresh-outline': RefreshCw,
    'remove-circle-outline': CircleMinus,
    'return-down-forward-outline': CornerDownLeft,
    search: Search,
    'server-outline': Server,
    'shield-outline': Shield,
    'shield-checkmark-outline': ShieldCheck,
    'speedometer-outline': Gauge,
    'stop-circle': CircleStop,
    'sparkles-outline': Sparkles,
    'stats-chart-outline': BarChart3,
    'sunny-outline': Sun,
    'swap-horizontal-outline': ArrowLeftRight,
    'terminal-outline': Terminal,
    'text-outline': Type,
    'time-outline': Clock3,
    'timer-outline': Timer,
    'trash-outline': CircleX,
    warning: TriangleAlert,
    'warning-outline': CircleAlert,
    'water-outline': Circle,
    'copy-outline': ClipboardCopy,
    'extension-puzzle-outline': Puzzle,
} satisfies Record<string, LucideIcon>;

export type AppIconName = keyof typeof ICON_MAP;

type AppIconProps = Omit<React.ComponentProps<typeof CircleHelp>, 'style'> & {
    name: AppIconName | string;
    style?: any;
};

export function AppIcon({ name, size = 24, color = 'currentColor', ...props }: AppIconProps) {
    const IconComponent = ICON_MAP[name as AppIconName] ?? CircleHelp;
    return <IconComponent size={size} color={color} {...props} />;
}
